### ISSUE TITLE
Choose license, add to all files.

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/diamond-android#19]
Hi @bgilbert  - should this repository be licensed under the EPL like `diamond-core-filters`?

**Comment by bamos** [comment]
Hi @bgilbert - I've added the following snippet to all the source
files in this repo. Can you take a look at the licensing statement at the
bottom of the README before we close this issue?

```
Diamond Android - Diamond filters for the Android platform

Copyright (c) 2013-2014 Carnegie Mellon University
All Rights Reserved.

This software is distributed under the terms of the Eclipse Public
License, Version 1.0 which can be found in the file named LICENSE.
ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
```

**Comment by bgilbert** [comment]
The README looks good.  `Diamond filters for the Android platform` isn't quite right, because your code provides a runner for existing filters, and not any new filters.

**Comment by bgilbert** [comment]
I used `Android library for running Diamond filters` in the repository description.  Better ideas welcome.  Could you get the text updated so we can close this bug?
